name: Riyoth's Blog
description: >
  This is my blog, I  write about my project, experiment and idea.
about: | 
  I’m a software developer with a strong background in DevOps,  networking, and cloud computing. I love solving real problems for real people. In the past, I’ve used Python, Django, and Flask to build small and large web applications. Tooling for the development team is a particular interest of mine. Ensuring fast feedback, rapid deployment, and rollback is the best way to deliver great software.

  I’ve started this blog to write about my project and experimentation. I will cover my work at [DreamHack Canada](http://dreamhack.ca), [CS Games](https://csgames.org) and other personal projects.

  Feel free to contact me by email or any of the following social media.

master_repo: false
url: "http://riyoth.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Pier-Olivier Clement
  avatar:         "https://avatars2.githubusercontent.com/u/952912?s=400&v=4"
  email:          "poclement+blog@riyoth.ca"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/Riyoth42
  github: https://github.com/riyoth
  stackexchange: 
  linkedin: https://www.linkedin.com/in/poclement
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: G-KB9Q4N5BSZ
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
