name: Riyoth's Blog
description: >
    This is my blog, I  write about my project, experiment and idea.
about: | 
  I'm a sysadmin/network admin with a strong desire to automate all the thing. My favorite tool to automate stuff Python and Ansible. Most of the time I work with Debian linux, Cisco, Juniper and Fortinet equipement.
  
  I've started this blog to write about my project and experimentation. I will cover my work at [DreamHack Canada](http://dreamhack.ca), [CS Games](https://csgames.org) and other personnal project.

  Feel free to contact me by email or any of the following social media.
    

master_repo: false
url: "http://riyoth.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Pier-Olivier Clement
  avatar:         "https://avatars2.githubusercontent.com/u/952912?s=400&v=4"
  email:          "poclement+blog@riyoth.ca"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/Riyoth42
  github: https://github.com/riyoth
  stackexchange: 
  linkedin: https://www.linkedin.com/in/poclement
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-127442593-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
